# Generated by Django 5.2.6 on 2025-12-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='bank_qr_code',
            field=models.ImageField(blank=True, help_text='Mã QR thanh toán', upload_to='artist/qr/'),
        ),
        migrations.AddField(
            model_name='orderprogress',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Đánh dấu là bản hoàn thiện cuối cùng'),
        ),
    ]
